name: Deploy MSA News Service

on:
  push:
    branches: [ main ]
    paths:
      - 'msa-news/**'
      - '.github/workflows/news-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # application.properties 파일 생성
      - name: News 서비스 설정 파일 생성
        run: |
          mkdir -p msa-news/src/main/resources
          echo "${{ secrets.MSA_NEWS_CONFIG }}" > msa-news/src/main/resources/application.properties
          echo "News 서비스 설정 파일 생성 완료"

      # 서비스 빌드
      - name: Build with Gradle
        run: |
          cd msa-news
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # EC2로 파일 업로드
      - name: EC2에 파일 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "msa-news/build/libs/*.jar,msa-news/Dockerfile,docker-compose.yml"
          target: "/home/${{ secrets.EC2_USER }}/app"
          strip_components: 0

      # EC2에서 서비스 실행
      - name: EC2에서 서비스 실행
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            # Docker 설치 확인
            if ! command -v docker &> /dev/null; then
              echo "Docker 설치 중..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker $USER
            fi
            
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose 설치 중..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            # 서비스 배포 및 실행
            cd /home/$USER/app
            
            # docker-compose.yml 수정 - 빌드 컨텍스트 수정
            cat > docker-compose.yml << 'EOL'
            version: '3.7'
            services:
              msa-news:
                build:
                  context: .
                  dockerfile: ./msa-news/Dockerfile
                container_name: msa-news
                ports:
                  - "8086:8086"
                environment:
                  - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://34.210.11.121:8761/eureka/
                networks:
                  - msa-network
                restart: always

            networks:
              msa-network:
                driver: bridge
            EOL
            
            # Dockerfile 수정
            cat > msa-news/Dockerfile << 'EOL'
            FROM openjdk:17-jdk-alpine
            WORKDIR /app
            COPY msa-news/build/libs/msa-sb-news-0.0.1-SNAPSHOT.jar app.jar
            EXPOSE 8086
            ENTRYPOINT ["java", "-jar", "app.jar"]
            EOL
            
            # 이전 서비스 중지 및 새 서비스 시작
            docker-compose stop msa-news || true
            docker-compose rm -f msa-news || true
            docker-compose up -d --build msa-news
            
            # 로그 확인
            sleep 5
            docker ps
            docker logs msa-news || true